### ISSUE TITLE
fove issues

### ISSUE THREAD

**Issue by sushmankvs287** [FoveHMD/UnityPlugin#1]
Parent directory must exist before creating asset at Assets/FoveUnityPlugin/Resources/FOVE Settings.asset.
UnityEditor.AssetDatabase:CreateAsset()
FoveSettings.FoveSettingsWindow:GetSettings() (at Assets/FoveUnitypllugin/Source/Editor/FoveSettingsEditor.cs:90)
FoveSettings.FoveSettingsWindow:RunOnce() (at Assets/FoveUnitypllugin/Source/Editor/FoveSettingsEditor.cs:73)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

UnityException: Creating asset at path Assets/FoveUnityPlugin/Resources/FOVE Settings.asset failed.
FoveSettings.FoveSettingsWindow.GetSettings () (at Assets/FoveUnitypllugin/Source/Editor/FoveSettingsEditor.cs:90)
FoveSettings.FoveSettingsWindow.RunOnce () (at Assets/FoveUnitypllugin/Source/Editor/FoveSettingsEditor.cs:73)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)

The above errors are encountered while running the program.

**Comment by xenux** [comment]
Thanks for the report, this seems to be fixed with the new version of the plugin.
